from flask import Flask, jsonify, request
from flask_cors import CORS
from supabase import create_client
from config import Config

def create_app():
    """Create and configure the Flask application"""
    Config.validate()
    
    app = Flask(__name__)
    app.config.from_object(Config)
    
    # Configure CORS
    CORS(app, 
         supports_credentials=True,
         origins=Config.CORS_ORIGINS,
         allow_headers=["Content-Type", "Authorization"],
         methods=["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"])
    
    # Initialize Supabase client
    supabase = create_client(Config.SUPABASE_URL, Config.SUPABASE_KEY)
    
    # Health check route
    @app.route("/", methods=["GET"])
    def health():
        return jsonify({
            "status": "Backend running",
            "version": "1.0.0"
        })
    
    # Test database connection
    @app.route("/test/db", methods=["GET"])
    def test_db():
        try:
            result = supabase.table("test").select("*").limit(1).execute()
            return jsonify({
                "status": "Database connected",
                "data": result.data
            }), 200
        except Exception as e:
            return jsonify({
                "status": "Database error", 
                "detail": str(e)
            }), 500
    
    # Get all test records
    @app.route("/test", methods=["GET"])
    def get_test_records():
        try:
            result = supabase.table("test").select("*").execute()
            return jsonify({
                "status": "success",
                "count": len(result.data),
                "data": result.data
            }), 200
        except Exception as e:
            return jsonify({
                "status": "error",
                "message": str(e)
            }), 500
    
    # Get test record by ID
    @app.route("/test/<test_id>", methods=["GET"])
    def get_test_record(test_id):
        try:
            result = supabase.table("test").select("*").eq("id", test_id).execute()
            
            if not result.data:
                return jsonify({
                    "status": "error",
                    "message": "Record not found"
                }), 404
            
            return jsonify({
                "status": "success",
                "data": result.data[0]
            }), 200
        except Exception as e:
            return jsonify({
                "status": "error",
                "message": str(e)
            }), 500
    
    # Create test record
    @app.route("/test", methods=["POST"])
    def create_test_record():
        try:
            data = request.get_json() or {}
            
            # Insert record (id and created_at will be auto-generated by Supabase)
            result = supabase.table("test").insert(data).execute()
            
            return jsonify({
                "status": "success",
                "message": "Record created",
                "data": result.data[0]
            }), 201
        except Exception as e:
            error_msg = str(e)
            
            # Check for RLS policy error
            if "row-level security" in error_msg.lower() or "42501" in error_msg:
                return jsonify({
                    "status": "error",
                    "message": "Row Level Security (RLS) policy error",
                    "detail": error_msg,
                    "fix": "Run 'ALTER TABLE test DISABLE ROW LEVEL SECURITY;' in Supabase SQL Editor. See fix_rls.md for details."
                }), 403
            
            return jsonify({
                "status": "error",
                "message": error_msg
            }), 500
    
    # Delete test record
    @app.route("/test/<test_id>", methods=["DELETE"])
    def delete_test_record(test_id):
        try:
            result = supabase.table("test").delete().eq("id", test_id).execute()
            
            return jsonify({
                "status": "success",
                "message": "Record deleted"
            }), 200
        except Exception as e:
            return jsonify({
                "status": "error",
                "message": str(e)
            }), 500
    
    return app

if __name__ == "__main__":
    app = create_app()
    app.run(
        host="0.0.0.0", 
        port=Config.PORT, 
        debug=(Config.FLASK_ENV == "development")
    )
